version: "3.7"

x-app-variables: &app-variables
  DB_URL: jdbc:postgresql://powerkr-test-db:5432/powerkr-test-db
  DB_USERNAME: user
  DB_PASSWORD: 1234
  PORT: 8080
x-postgres-variables: &postgres-variables
  POSTGRES_DB: powerkr-test-db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: 1234

services:
  db:
    image: postgres
    container_name: powerkr-test-db
    ports:
      - "54321:5432"
    environment:
      <<: *postgres-variables
    volumes:
      - powerkr-test-db-volume:/var/lib/postgresql/data

  app:
    image: edsonmendes/powerkr-test-api:latest
    container_name: powerkr-test-app
    depends_on:
      - db
    ports:
      - "8888:8080"
    environment:
      <<: *app-variables

volumes:
  powerkr-test-db-volume: